[tox]
envlist = dev, py
skipsdist = True

[testenv:dev]
description = Development environment with editable install
deps =
    -r dev-requirements.txt
commands =
    pip install --editable .
    pytest -q
allowlist_externals = pytest

[testenv:py]
description = Production-like environment
deps =
    -r requirements.txt
commands =
    pip install .
    pytest -q
allowlist_externals = pytest
